"""Claude Agent SDK adapter (final draft §12.3): the production `AgentRuntime`.

Wraps `claude_agent_sdk.query`, which is async and one-shot.

**Environment scrubbing (red team R-A3).** The SDK's subprocess transport
spawns the CLI with `{**os.environ, **options.env}` — the *entire* parent
environment, with `options.env` merged on top. Run from inside the
controller process, that would hand an agent subprocess every `FACTORY_*`
secret (database URL, GitHub App keys, the LiteLLM master key, ...) the
controller itself holds. `ClaudeAgentOptions` has no "replace, don't merge"
mode, so this adapter routes the spawn through a tiny generated wrapper
script (`cli_path`): the SDK still spawns it with the poisoned environment,
but the wrapper's first and only act is to filter that environment down to
`scrub_env`'s allowlist (`PATH`, `HOME`, `LANG`/`LC_ALL`, the gateway URL/key,
proxy vars) and `execve` into the real CLI with nothing else. `HOME` is
additionally overridden per run to a fresh, empty per-session temp directory
(via `options.env`, which the wrapper also passes through), so the agent
never sees the controller's own `~/.gitconfig`, `~/.npmrc` or `~/.claude/`.

**Tool permissions.** `can_use_tool` allows a call only if the tool is
already in the task's `allowed_tools`; anything else goes through
`on_tool_approval`, and a missing callback or a False/None answer denies the
call (final draft §12.3 "on_tool_approval").

**No implicit provider key.** The only credential this adapter ever hands
the SDK is the per-mission gateway key (`RuntimeRequest.gateway_key`),
pointed at the gateway via `ANTHROPIC_BASE_URL`/`ANTHROPIC_API_KEY`. If a
request has no gateway key, `run`/`resume` refuse outright — an agent must
never fall back to a raw provider key from the ambient environment — unless
the adapter was explicitly constructed with `allow_direct_provider_key=True`
for local dev without a gateway running.
"""
from __future__ import annotations

import asyncio
import dataclasses
import logging
import os
import shutil
import tempfile
from collections.abc import Awaitable, Callable, Coroutine, Mapping
from typing import Any

from claude_agent_sdk import (
    AssistantMessage,
    ClaudeAgentOptions,
    ClaudeSDKError,
    PermissionResultAllow,
    PermissionResultDeny,
    ResultError,
    ResultMessage,
    TextBlock,
    get_session_messages,
    query,
)

from ..models import RuntimeRequest, RuntimeResult

logger = logging.getLogger(__name__)

# ResultMessage.subtype values that mean the run stopped because it ran out of
# turns or money, not because it failed outright.
_BUDGET_SUBTYPES = frozenset({"error_max_turns", "error_max_budget_usd"})

# The ONLY environment variable names an agent subprocess is allowed to see
# (red team R-A3). Everything else the controller's own process holds --
# every FACTORY_* setting, database URLs, GitHub App keys, the LiteLLM
# master key -- is dropped, however it ended up in this process's env.
_ALLOWED_ENV_NAMES = frozenset({
    "PATH", "HOME", "LANG", "LC_ALL",
    "ANTHROPIC_BASE_URL", "ANTHROPIC_API_KEY",
    "HTTP_PROXY", "HTTPS_PROXY", "NO_PROXY",
    "http_proxy", "https_proxy", "no_proxy",
})


def scrub_env(env: Mapping[str, str]) -> dict[str, str]:
    """Filter `env` down to `_ALLOWED_ENV_NAMES`. Pure, and used by the generated
    wrapper script itself (imported there), so the allowlist can never drift
    between what this module documents and what actually gets exec'd."""
    return {k: v for k, v in env.items() if k in _ALLOWED_ENV_NAMES}


_WRAPPER_SOURCE = '''#!/usr/bin/env python3
"""Generated by factory.runtime.claude._write_env_scrubbing_wrapper.

execve's into the real Claude CLI with a scrubbed environment, dropping
everything the parent process merged in except an explicit allowlist. See
factory.runtime.claude for why this exists (red team R-A3).
"""
import os
import sys

from factory.runtime.claude import scrub_env

TARGET_CLI = {target_cli!r}

if __name__ == "__main__":
    os.execve(TARGET_CLI, [TARGET_CLI] + sys.argv[1:], scrub_env(os.environ))
'''


def _write_env_scrubbing_wrapper(target_cli: str) -> str:
    """Write the wrapper script for `target_cli` to a fresh temp file and return its path."""
    fd, path = tempfile.mkstemp(prefix="factory-claude-wrapper-", suffix=".py")
    with os.fdopen(fd, "w") as f:
        f.write(_WRAPPER_SOURCE.format(target_cli=target_cli))
    os.chmod(path, 0o700)
    return path


@dataclasses.dataclass
class _SessionContext:
    """What `resume`/`checkpoint`/`cancel` need, keyed by session_id."""
    workdir: str
    model: str
    max_turns: int | None
    budget_usd: float | None
    allowed_tools: tuple
    gateway_key: str | None
    gateway_url: str | None
    system_prompt: str | None
    home_dir: str | None
    on_tool_approval: Callable[[str, dict], bool] | None


def _run_sync(coro: Coroutine[Any, Any, RuntimeResult]) -> RuntimeResult:
    """Run `coro` to completion. Raises if already inside a running event loop:
    joining a helper thread there would silently hide double-loop bugs in the
    caller, so `arun`/`aresume` are the only supported path from async code
    (code review Q-H4)."""
    try:
        asyncio.get_running_loop()
    except RuntimeError:
        return asyncio.run(coro)
    coro.close()
    raise RuntimeError(
        "ClaudeRuntime.run()/resume() cannot be called from inside a running event "
        "loop; use arun()/aresume() instead"
    )


class ClaudeRuntime:
    """`AgentRuntime` backed by the Claude Agent SDK."""

    def __init__(self, *, cli_path: str | None = None, allow_direct_provider_key: bool = False,
                 allow_unscrubbed_env: bool = False):
        self._sessions: dict[str, _SessionContext] = {}
        self._allow_direct_provider_key = allow_direct_provider_key
        self._allow_unscrubbed_env = allow_unscrubbed_env
        self._target_cli = cli_path or shutil.which("claude")
        self._wrapper_path: str | None = None
        self._home_dirs: set[str] = set()

    def _wrapper(self) -> str | None:
        if self._target_cli is None:
            # Fail closed (red team R-A3): without the wrapper the agent subprocess would
            # inherit this process's full environment, secrets included.
            if not self._allow_unscrubbed_env:
                raise RuntimeError(
                    "no Claude CLI found: set FACTORY_CLAUDE_CLI_PATH (or pass cli_path=) so the "
                    "environment-scrubbing wrapper can be applied; refusing to run an agent "
                    "with the controller's unscrubbed environment")
            logger.warning("running an agent WITHOUT environment scrubbing (allow_unscrubbed_env=True)")
            return None
        if self._wrapper_path is None:
            self._wrapper_path = _write_env_scrubbing_wrapper(self._target_cli)
        return self._wrapper_path

    # ── option construction ──────────────────────────────────────────────
    def _make_can_use_tool(
        self,
        allowed_tools: tuple,
        on_tool_approval: Callable[[str, dict], bool] | None,
    ) -> Callable[[str, dict, Any], Awaitable[PermissionResultAllow | PermissionResultDeny]]:
        allowed = set(allowed_tools)

        async def can_use_tool(tool_name: str, tool_input: dict, _context: Any):
            if tool_name in allowed:
                return PermissionResultAllow()
            approved = bool(on_tool_approval(tool_name, tool_input)) if on_tool_approval else False
            if approved:
                return PermissionResultAllow()
            return PermissionResultDeny(message=f"tool {tool_name!r} is not permitted for this task")

        return can_use_tool

    def _build_options(
        self,
        *,
        workdir: str,
        model: str,
        max_turns: int | None,
        budget_usd: float | None,
        allowed_tools: tuple,
        system_prompt: str | None,
        gateway_key: str | None,
        gateway_url: str | None,
        home_dir: str | None,
        on_tool_approval: Callable[[str, dict], bool] | None,
        resume: str | None = None,
    ) -> ClaudeAgentOptions:
        env: dict[str, str] = {}
        if gateway_url:
            env["ANTHROPIC_BASE_URL"] = gateway_url
        if gateway_key:
            # The gateway key only: never a raw provider key (final draft §13.1 #7).
            env["ANTHROPIC_API_KEY"] = gateway_key
        if home_dir:
            env["HOME"] = home_dir
        return ClaudeAgentOptions(
            cwd=workdir,
            model=model,
            max_turns=max_turns,
            max_budget_usd=budget_usd,
            allowed_tools=list(allowed_tools),
            system_prompt=system_prompt,
            # No filesystem settings: repo-level .claude/ in the sandbox is agent-writable
            # and must never configure the agent (red team #2).
            setting_sources=None,
            env=env,
            cli_path=self._wrapper(),
            can_use_tool=self._make_can_use_tool(allowed_tools, on_tool_approval),
            resume=resume,
        )

    def _require_gateway_key(self, request: RuntimeRequest) -> None:
        if request.gateway_key or self._allow_direct_provider_key:
            return
        raise RuntimeError(
            "ClaudeRuntime requires a per-mission gateway key (RuntimeRequest.gateway_key); "
            "construct it with allow_direct_provider_key=True to run without one for local dev"
        )

    # ── running the SDK's async generator ───────────────────────────────
    async def _collect(self, prompt: str, options: ClaudeAgentOptions) -> RuntimeResult:
        output_parts: list[str] = []
        result_message: ResultMessage | None = None
        try:
            async for message in query(prompt=prompt, options=options):
                if isinstance(message, AssistantMessage):
                    for block in message.content:
                        if isinstance(block, TextBlock):
                            output_parts.append(block.text)
                elif isinstance(message, ResultMessage):
                    result_message = message
        except ResultError as exc:
            status = "budget_exceeded" if exc.subtype in _BUDGET_SUBTYPES else "failed"
            return RuntimeResult(
                session_id=exc.session_id or "",
                status=status,
                output_text="\n".join(output_parts),
                error=exc.result or "; ".join(exc.errors) or str(exc),
            )
        except ClaudeSDKError as exc:
            return RuntimeResult(session_id="", status="failed", output_text="\n".join(output_parts), error=str(exc))

        return self._map_result(result_message, "\n".join(output_parts))

    def _map_result(self, result: ResultMessage | None, output_text: str) -> RuntimeResult:
        if result is None:
            return RuntimeResult(session_id="", status="failed", output_text=output_text,
                                  error="the SDK produced no result message")
        if result.subtype in _BUDGET_SUBTYPES:
            status = "budget_exceeded"
        elif result.is_error:
            status = "failed"
        else:
            status = "completed"
        usage = result.usage or {}
        tokens = sum(v for k, v in usage.items() if k.endswith("_tokens") and isinstance(v, int))
        error = None
        if status != "completed":
            error = result.result or "run did not complete successfully"
        return RuntimeResult(
            session_id=result.session_id,
            status=status,
            output_text=output_text or (result.result or ""),
            usage_usd=result.total_cost_usd or 0.0,
            tokens=tokens,
            num_turns=result.num_turns,
            error=error,
        )

    def _remember_session(self, result: RuntimeResult, ctx: _SessionContext) -> None:
        if result.session_id:
            self._sessions[result.session_id] = ctx

    # ── AgentRuntime (sync) ──────────────────────────────────────────────
    def run(self, request: RuntimeRequest, *, on_tool_approval: Callable[[str, dict], bool] | None = None) -> RuntimeResult:
        return _run_sync(self._arun_coro(request, on_tool_approval=on_tool_approval))

    def resume(self, session_id: str, message: str) -> RuntimeResult:
        return _run_sync(self._aresume_coro(session_id, message))

    # ── AgentRuntime (async) — the only supported path from a running loop ─
    async def arun(self, request: RuntimeRequest, *, on_tool_approval: Callable[[str, dict], bool] | None = None) -> RuntimeResult:
        return await self._arun_coro(request, on_tool_approval=on_tool_approval)

    async def aresume(self, session_id: str, message: str) -> RuntimeResult:
        return await self._aresume_coro(session_id, message)

    async def _arun_coro(self, request: RuntimeRequest, *, on_tool_approval=None) -> RuntimeResult:
        self._require_gateway_key(request)
        home_dir = tempfile.mkdtemp(prefix="factory-agent-home-")
        self._home_dirs.add(home_dir)
        options = self._build_options(
            workdir=request.workdir,
            model=request.model,
            max_turns=request.max_turns,
            budget_usd=request.budget_usd,
            allowed_tools=request.allowed_tools,
            system_prompt=request.system_prompt,
            gateway_key=request.gateway_key,
            gateway_url=request.gateway_url,
            home_dir=home_dir,
            on_tool_approval=on_tool_approval,
        )
        result = await self._collect(request.prompt, options)
        ctx = _SessionContext(
            workdir=request.workdir,
            model=request.model,
            max_turns=request.max_turns,
            budget_usd=request.budget_usd,
            allowed_tools=request.allowed_tools,
            gateway_key=request.gateway_key,
            gateway_url=request.gateway_url,
            system_prompt=request.system_prompt,
            home_dir=home_dir,
            on_tool_approval=on_tool_approval,
        )
        self._remember_session(result, ctx)
        return result

    async def _aresume_coro(self, session_id: str, message: str) -> RuntimeResult:
        ctx = self._sessions.get(session_id)
        if ctx is None:
            raise RuntimeError(f"cannot resume unknown session {session_id!r}: no cached run() context")
        if not ctx.gateway_key and not self._allow_direct_provider_key:
            raise RuntimeError(
                "ClaudeRuntime requires a per-mission gateway key to resume a session; "
                "construct it with allow_direct_provider_key=True to run without one for local dev"
            )
        # resume keeps the session's own limits: a follow-up turn is still bound by
        # the task's original max_turns/budget_usd, not an unlimited default.
        options = self._build_options(
            workdir=ctx.workdir,
            model=ctx.model,
            max_turns=ctx.max_turns,
            budget_usd=ctx.budget_usd,
            allowed_tools=ctx.allowed_tools,
            system_prompt=ctx.system_prompt,
            gateway_key=ctx.gateway_key,
            gateway_url=ctx.gateway_url,
            home_dir=ctx.home_dir,
            on_tool_approval=ctx.on_tool_approval,
            resume=session_id,
        )
        result = await self._collect(message, options)
        self._remember_session(result, ctx)
        return result

    def cancel(self, session_id: str) -> None:
        # `query()` is one-shot and stateless: there is no in-flight run to interrupt
        # from here. Dropping the cached context (and its per-session HOME) is the
        # honest thing this adapter can do — it stops `resume` from continuing a
        # session the controller gave up on.
        ctx = self._sessions.pop(session_id, None)
        if ctx is not None:
            if ctx.home_dir:
                shutil.rmtree(ctx.home_dir, ignore_errors=True)
                self._home_dirs.discard(ctx.home_dir)
            logger.info("dropped cached context for cancelled session %s", session_id)

    def close(self) -> None:
        """Remove the generated env-scrubbing wrapper script and every per-run HOME
        temp directory this instance ever created."""
        if self._wrapper_path:
            try:
                os.remove(self._wrapper_path)
            except OSError:
                pass
            self._wrapper_path = None
        for home_dir in self._home_dirs:
            shutil.rmtree(home_dir, ignore_errors=True)
        self._home_dirs.clear()

    def checkpoint(self, session_id: str) -> dict:
        """Session state persisted OUTSIDE the sandbox (final draft §12.3)."""
        ctx = self._sessions.get(session_id)
        workdir = ctx.workdir if ctx else None
        try:
            messages = get_session_messages(session_id, directory=workdir)
        except Exception:  # noqa: BLE001 - checkpointing must never raise
            logger.warning("could not read session transcript for %s", session_id, exc_info=True)
            messages = []
        return {
            "session_id": session_id,
            "workdir": workdir,
            "messages": [dataclasses.asdict(m) for m in messages],
        }
