"""Ports: the interfaces between modules (final draft §12.2, §12.3).

Every external dependency sits behind one of these Protocols. Each port has:
  - a real adapter (production), and
  - a fake adapter (tests + `factory demo`), with the SAME semantics.
The orchestrator (factory.pipeline) depends only on these Protocols.
"""
from datetime import datetime
from typing import Callable, Iterable, Protocol, runtime_checkable

from .controller.approvals import ApprovalRequest
from .controller.intents import Intent
from .models import (CheckResult, DecisionPacket, DeployReceipt, Diff, EvidenceBundle, ExecResult,
                     MissionRecord, RuntimeRequest, RuntimeResult, SandboxHandle, TaskRecord, WorkItem)


class ConcurrentUpdate(Exception):
    """Compare-and-swap failed: the record changed since it was read."""


class NotFound(KeyError):
    pass


@runtime_checkable
class Clock(Protocol):
    def now(self) -> datetime: ...


# ── State (M3/M12) ────────────────────────────────────────────────────────────────────
@runtime_checkable
class ApprovalStorePort(Protocol):
    """Semantics defined by factory.controller.approvals.ApprovalStore (reference impl)."""
    def add(self, request: ApprovalRequest) -> ApprovalRequest: ...
    def get(self, request_id: str) -> ApprovalRequest: ...
    def decide(self, request_id: str, *, approver: str, roles, decision: str, content_hash: str,
               now: datetime) -> ApprovalRequest: ...
    def consume(self, request_id: str, *, executor: str, now: datetime, state_version: int,
                content_hash: str, policy_version: str) -> int: ...
    def invalidate_for_artifact(self, artifact: str, reason: str) -> list[str]: ...
    def list_open(self, mission_id: str | None = None) -> list[ApprovalRequest]: ...


@runtime_checkable
class IntentLogPort(Protocol):
    """Semantics defined by factory.controller.intents.IntentLog (reference impl)."""
    def get(self, operation_id: str) -> Intent | None: ...
    def begin(self, operation_id: str) -> Intent: ...
    def complete(self, operation_id: str, receipt) -> None: ...
    def pending(self) -> list[Intent]: ...


@runtime_checkable
class StateStore(Protocol):
    approvals: ApprovalStorePort
    intents: IntentLogPort

    def create_mission(self, mission: MissionRecord) -> MissionRecord: ...
    def get_mission(self, mission_id: str) -> MissionRecord: ...
    def update_mission(self, mission_id: str, *, expected_version: int, **changes) -> MissionRecord:
        """CAS update: raises ConcurrentUpdate if state_version != expected_version. Bumps state_version."""
    def list_missions(self, *, state: str | None = None, product: str | None = None) -> list[MissionRecord]: ...
    def find_mission_by_work_item(self, work_item_id: str) -> MissionRecord | None: ...

    def create_task(self, task: TaskRecord) -> TaskRecord: ...
    def get_task(self, task_id: str) -> TaskRecord: ...
    def update_task(self, task_id: str, **changes) -> TaskRecord: ...
    def list_tasks(self, mission_id: str) -> list[TaskRecord]: ...

    def save_evidence(self, bundle: EvidenceBundle) -> None: ...
    def get_evidence(self, mission_id: str, revision: str | None = None) -> EvidenceBundle | None: ...
    def save_packet(self, packet: DecisionPacket) -> None: ...
    def get_packet(self, request_id: str) -> DecisionPacket: ...

    def append_event(self, mission_id: str, kind: str, payload: dict) -> None: ...
    def list_events(self, mission_id: str) -> list[dict]: ...


# ── GitHub (M1/M3/M11 edges) ──────────────────────────────────────────────────────────
@runtime_checkable
class GitHubPort(Protocol):
    """Two deterministic identities in production: the push bot and the merge bot (§11, §13.2)."""
    def get_issue(self, repo: str, number: int) -> WorkItem: ...
    def comment_issue(self, repo: str, number: int, body: str) -> None: ...
    def mirror_labels(self, repo: str, number: int, *, add: Iterable[str] = (), remove: Iterable[str] = ()) -> None: ...
    def head_commit(self, repo: str, branch: str = "main") -> str: ...
    def push_diff(self, repo: str, *, branch: str, diff: Diff, message: str) -> str:
        """Push bot: apply diff on base_commit, push branch, return commit sha. Rejects AC8 paths."""
    def open_pr(self, repo: str, *, head: str, base: str, title: str, body: str) -> int: ...
    def pr_head_sha(self, repo: str, number: int) -> str: ...
    def check_runs(self, repo: str, sha: str) -> list[CheckResult]: ...
    def pr_reviews(self, repo: str, number: int) -> list[dict]:
        """[{"login": str, "state": "APPROVED"|"CHANGES_REQUESTED"|..., "commit_id": str}]"""
    def merge_pr(self, repo: str, number: int, *, expected_head_sha: str) -> str:
        """Merge bot: merge only if head sha matches; return merge commit sha."""
    def revert_commit(self, repo: str, sha: str, *, branch: str = "main") -> str: ...


# ── Agents (M7), sandboxes (M8), budgets (M6) ────────────────────────────────────────
@runtime_checkable
class AgentRuntime(Protocol):
    def run(self, request: RuntimeRequest, *, on_tool_approval: Callable[[str, dict], bool] | None = None) -> RuntimeResult: ...
    def resume(self, session_id: str, message: str) -> RuntimeResult: ...
    def cancel(self, session_id: str) -> None: ...
    def checkpoint(self, session_id: str) -> dict:
        """Session state persisted OUTSIDE the sandbox so work survives sandbox loss."""


@runtime_checkable
class SandboxPort(Protocol):
    def create(self, repo: str, base_commit: str) -> SandboxHandle: ...
    def exec(self, handle: SandboxHandle, cmd: list[str], *, network: bool = False,
             timeout_s: int = 900) -> ExecResult:
        """Code execution defaults to NO network (§13.1 #2)."""
    def capture_diff(self, handle: SandboxHandle) -> Diff: ...
    def destroy(self, handle: SandboxHandle) -> None: ...


@runtime_checkable
class BudgetGateway(Protocol):
    """External budget enforcement at the LLM gateway (§13.1 #7)."""
    def create_key(self, mission_id: str, max_usd: float) -> str: ...
    def spent(self, key: str) -> float: ...
    def revoke(self, key: str) -> None: ...


# ── Humans (inbox) ────────────────────────────────────────────────────────────────────
@runtime_checkable
class Notifier(Protocol):
    def decision_requested(self, packet: DecisionPacket, *, inbox_url: str) -> None: ...
    def info(self, text: str) -> None: ...


# ── Verification (M10) ────────────────────────────────────────────────────────────────
@runtime_checkable
class HoldoutRunner(Protocol):
    def run(self, product: str, *, staging_url: str, artifact: str) -> tuple[int, int]:
        """Black-box scenarios from a separate repo; returns (passed, total) ONLY."""


# ── Release (M11) ─────────────────────────────────────────────────────────────────────
@runtime_checkable
class DeployTarget(Protocol):
    def build(self, repo: str, sha: str) -> str:
        """Build once; return an immutable artifact digest (sha256:...)."""
    def deploy(self, artifact: str, *, environment: str, operation_id: str, fencing_token: int) -> DeployReceipt: ...
    def healthy(self, environment: str) -> bool: ...
    def rollback(self, environment: str, *, to_artifact: str | None, operation_id: str) -> DeployReceipt: ...
    def url(self, environment: str) -> str: ...


@runtime_checkable
class FlagProvider(Protocol):
    def create(self, flag: str) -> None:
        """Create a default-OFF flag (one per mission)."""
    def set_rollout(self, flag: str, percent: int) -> None: ...
    def kill(self, flag: str) -> None: ...
    def rollout(self, flag: str) -> int: ...
